#!/usr/bin/env python3
"""Write crates/mirsam-core/src/charname.rs from the Unicode Character Database.

A coverage finding has to name the character a font cannot draw, or a reviewer
is left comparing codepoints by eye. The names are Unicode's own, and Unicode
guarantees they never change once assigned, so a committed table is exactly as
correct as the day it was generated and a regeneration only ever adds rows.

The data comes from Python's own `unicodedata`, which is the UCD the
interpreter ships. No network, no third-party module, and nothing here has
seen `ttf-parser` or `rustybuzz` — the same reason `make-shaping-fixture.py`
refuses `fontTools`. Run `make names` and commit the diff; never edit the
generated file.

The four ranges below are the Arabic script in logical order: the block
itself, the Supplement, and Extended-A and -B. The presentation-form blocks
are deliberately absent. Pre-shaped text is `presentation-forms`' business and
a defect in its own right, so whether some font happens to draw U+FB50 is not
a question about the document that anyone should act on.
"""

from __future__ import annotations

import pathlib
import unicodedata

RANGES = [
    (0x0600, 0x06FF, "Arabic"),
    (0x0750, 0x077F, "Arabic Supplement"),
    (0x0870, 0x089F, "Arabic Extended-B"),
    (0x08A0, 0x08FF, "Arabic Extended-A"),
]

OUT = pathlib.Path(__file__).resolve().parent.parent / "crates/mirsam-core/src/charname.rs"

HEADER = '''\
//! Unicode names for the Arabic script, in logical order.
//!
//! **Generated by `scripts/make-char-names.py`; run `make names` to refresh
//! it and never edit it by hand.** The data is the Unicode Character Database
//! that Python ships, read through `unicodedata` and nothing else.
//!
//! A coverage finding has to say *which* character a font cannot draw, and
//! `U+0679` on its own asks a reviewer to look it up. `ARABIC LETTER TTEH`
//! does not. Unicode's stability policy guarantees an assigned name is never
//! changed or reused, so a committed table stays correct and a regeneration
//! only ever adds rows.
//!
//! ## What the table covers, and what it refuses to
//!
//! The Arabic block, the Supplement, and Extended-A and -B: the Arabic script
//! as a document is supposed to store it. [`name`] answers `None` for
//! everything else, which is the difference between "this character is not
//! Arabic script" and "this table has nothing to say", and callers render the
//! codepoint alone rather than inventing a name for it.
//!
//! The presentation-form blocks are deliberately absent. Pre-shaped text is
//! [`crate::script::is_presentation_form`]'s business and a blocking defect in
//! its own right; whether a font draws U+FB50 is not a question anyone should
//! act on, because the answer for correctly stored text is that U+FB50 is not
//! there.

/// The Unicode name of `c`, for the Arabic script in logical order.
///
/// `None` for every other character — see the module documentation.
pub fn name(c: char) -> Option<&'static str> {
    NAMES
        .binary_search_by_key(&(c as u32), |(codepoint, _)| *codepoint)
        .ok()
        .map(|i| NAMES[i].1)
}

/// Whether `c` is a format character: one that carries meaning but is never
/// drawn.
///
/// A font is not missing a glyph it was never meant to have. U+0600 ARABIC
/// NUMBER SIGN and its kin prefix a numeral, U+06DD ARABIC END OF AYAH
/// encloses a verse number, and U+061C ARABIC LETTER MARK is a bidi control
/// (see [`crate::controls`]) — none of them is a shape, and reporting a font
/// for having no glyph for one would be reporting every font there is.
pub fn is_format(c: char) -> bool {
    matches!(c as u32, FORMAT_PATTERN)
}

'''


def main() -> None:
    entries: list[tuple[int, str]] = []
    formats: list[int] = []
    counts: list[tuple[str, int]] = []

    for first, last, block in RANGES:
        found = 0
        for codepoint in range(first, last + 1):
            char = chr(codepoint)
            try:
                unicode_name = unicodedata.name(char)
            except ValueError:
                continue  # unassigned: the table says nothing about it
            entries.append((codepoint, unicode_name))
            if unicodedata.category(char) == "Cf":
                formats.append(codepoint)
            found += 1
        counts.append((block, found))

    entries.sort()

    lines = [
        HEADER.replace(
            "FORMAT_PATTERN",
            "\n        | ".join(f"0x{codepoint:04X}" for codepoint in sorted(formats)),
        )
    ]

    lines.append(
        "/// Every assigned character of the four blocks, ascending, for the binary\n"
        "/// search in [`name`].\n"
        f"///\n"
        f"/// Unicode {unicodedata.unidata_version}: "
        + ", ".join(f"{block} {found}" for block, found in counts)
        + ".\n"
        f"static NAMES: [(u32, &str); {len(entries)}] = [\n"
    )
    for codepoint, unicode_name in entries:
        lines.append(f'    (0x{codepoint:04X}, "{unicode_name}"),\n')
    lines.append("];\n")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}: {len(entries)} names, "
          f"{len(formats)} format characters, Unicode {unicodedata.unidata_version}")


if __name__ == "__main__":
    main()
