//! Round-trip: a rewrite must return every part it was not asked to change,
//! bit for bit.
//!
//! This is the foundation the repair milestone stands on. Every mutation test
//! that follows asserts "exactly this changed and nothing else" — a claim that
//! is worthless unless "nothing else" is independently proven first.
//!
//! ## What is asserted, and what is not
//!
//! For every entry the rewrite did not edit, this suite asserts that the name
//! (as text and as stored bytes), position in the package, compression method,
//! last-modified time, CRC-32, compressed size, uncompressed size and **raw
//! compressed bytes** are identical. Nothing is decompressed and re-deflated, so no entry can be
//! silently re-encoded.
//!
//! Whole-file byte equality is deliberately *not* asserted, because it does not
//! hold and cannot be made to hold through the `zip` crate. Three container
//! bookkeeping fields are normalised on write:
//!
//! | field | source | rewrite |
//! |---|---|---|
//! | local + central `version needed to extract`, stored entries | 20 | 10 |
//! | central `version made by`, host byte | 0 (MS-DOS) | 3 (Unix) |
//! | central `external attributes` | follows the host byte | follows the host byte |
//!
//! Both encodings are spec-valid; the `zip` crate's is arguably the more
//! correct, since 10 is the true minimum for a stored entry. None of the three
//! can alter a document's content. The per-entry assertions below are the
//! stronger and more useful claim in any case: when one fails it names the
//! entry and the field, where a whole-file `memcmp` would only report an offset.
//!
//! The fixture is generated by `scripts/make-torture-fixture.py` using Python's
//! `zipfile` — deliberately not the `zip` crate under test. A fixture built by
//! the same library would only prove the writer agrees with itself.

use mirsam_ooxml::package::{Edits, Package};
use std::io::Read;
use std::path::{Path, PathBuf};

const TORTURE: &str = "torture.pptx";

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures")
        .join(name)
}

/// Everything about one entry that a rewrite must preserve.
#[derive(Debug, PartialEq, Eq)]
struct Entry {
    name: String,
    /// The name's bytes as stored, so a mangled UTF-8 entry name is caught.
    name_raw: Vec<u8>,
    method: String,
    modified: Option<String>,
    crc32: u32,
    compressed_size: u64,
    uncompressed_size: u64,
    /// The compressed bytes exactly as stored — never decompressed.
    raw: Vec<u8>,
}

/// Read every entry of a package in stored order, without decompressing.
fn manifest(path: &Path) -> Vec<Entry> {
    let file = std::fs::File::open(path).unwrap();
    let mut archive = zip::ZipArchive::new(std::io::BufReader::new(file)).unwrap();
    let mut out = Vec::new();
    for i in 0..archive.len() {
        let mut entry = archive.by_index_raw(i).unwrap();
        let name = entry.name().to_string();
        let name_raw = entry.name_raw().to_vec();
        let method = format!("{:?}", entry.compression());
        let modified = entry.last_modified().map(|d| format!("{d:?}"));
        let crc32 = entry.crc32();
        let compressed_size = entry.compressed_size();
        let uncompressed_size = entry.size();
        let mut raw = Vec::new();
        entry.read_to_end(&mut raw).unwrap();
        out.push(Entry {
            name,
            name_raw,
            method,
            modified,
            crc32,
            compressed_size,
            uncompressed_size,
            raw,
        });
    }
    out
}

/// A scratch directory that removes itself.
struct Scratch(PathBuf);

impl Scratch {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!("mirsam-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        Self(dir)
    }
    fn join(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Assert two manifests agree entry for entry, reporting the first field that
/// differs rather than dumping two blobs of compressed bytes.
fn assert_entries_identical(before: &[Entry], after: &[Entry], skip: &[&str]) {
    let names_before: Vec<&str> = before.iter().map(|e| e.name.as_str()).collect();
    let names_after: Vec<&str> = after.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(
        names_before, names_after,
        "entry names or their order changed"
    );

    for (b, a) in before.iter().zip(after) {
        if skip.contains(&b.name.as_str()) {
            continue;
        }
        assert_eq!(
            b.name_raw, a.name_raw,
            "{}: the stored name bytes changed",
            b.name
        );
        assert_eq!(b.method, a.method, "{}: compression method changed", b.name);
        assert_eq!(b.modified, a.modified, "{}: timestamp changed", b.name);
        assert_eq!(b.crc32, a.crc32, "{}: CRC-32 changed", b.name);
        assert_eq!(
            b.uncompressed_size, a.uncompressed_size,
            "{}: uncompressed size changed",
            b.name
        );
        assert_eq!(
            b.compressed_size, a.compressed_size,
            "{}: compressed size changed — the entry was re-encoded",
            b.name
        );
        assert!(
            b.raw == a.raw,
            "{}: raw compressed bytes differ at offset {:?}",
            b.name,
            b.raw.iter().zip(&a.raw).position(|(x, y)| x != y)
        );
    }
}

#[test]
fn rewriting_with_no_edits_preserves_every_entry() {
    let src = fixture(TORTURE);
    let scratch = Scratch::new("roundtrip");
    let out = scratch.join("out.pptx");

    let pkg = Package::open(&src).unwrap();
    let applied = pkg.rewrite(&out, &Edits::new()).unwrap();
    assert_eq!(applied, 0, "no edits supplied, so none may be applied");

    assert_entries_identical(&manifest(&src), &manifest(&out), &[]);
}

#[test]
fn the_acceptance_deck_carries_every_structure_the_plan_names() {
    // Guards the fixture itself. If someone regenerates it without these, the
    // round-trip test above silently stops proving what it claims to prove.
    let pkg = Package::open(fixture(TORTURE)).unwrap();
    let names = pkg.part_names().unwrap();

    assert!(
        names.iter().any(|n| n == "ppt/notesSlides/notesSlide1.xml"),
        "speaker notes missing"
    );
    assert!(
        names.iter().any(|n| n == "ppt/charts/chart1.xml"),
        "embedded chart missing"
    );
    assert!(
        names
            .iter()
            .any(|n| n.ends_with("Microsoft_Excel_Sheet1.xlsx")),
        "the chart's embedded workbook — a ZIP inside the ZIP — is missing"
    );
    assert!(
        names.iter().any(|n| n.contains('%')),
        "no percent-encoded item name; a rewriter that decodes names goes untested"
    );
    assert!(
        names.iter().all(|n| n.is_ascii()),
        "a non-ASCII item name; PowerPoint 2016 does not open a package with \
         one in any encoding (#9)"
    );
    assert!(
        pkg.read_text("ppt/slides/slide1.xml")
            .unwrap()
            .contains("mc:AlternateContent"),
        "no mc:AlternateContent block"
    );

    // Mixed compression is what makes re-encoding detectable.
    let file = std::fs::File::open(fixture(TORTURE)).unwrap();
    let mut archive = zip::ZipArchive::new(std::io::BufReader::new(file)).unwrap();
    let mut methods = std::collections::BTreeSet::new();
    for i in 0..archive.len() {
        methods.insert(format!(
            "{:?}",
            archive.by_index_raw(i).unwrap().compression()
        ));
    }
    assert!(
        methods.len() > 1,
        "every entry uses one compression method; re-encoding would go unnoticed"
    );
}

#[test]
fn an_edit_changes_that_part_and_nothing_else() {
    let src = fixture(TORTURE);
    let scratch = Scratch::new("edit");
    let out = scratch.join("out.pptx");

    let pkg = Package::open(&src).unwrap();
    let edited = "ppt/slides/slide1.xml";
    let replacement = pkg
        .read_text(edited)
        .unwrap()
        .replace(r#"rtl="0""#, r#"rtl="1""#);
    assert_ne!(
        replacement,
        pkg.read_text(edited).unwrap(),
        "the replacement must actually differ, or this test proves nothing"
    );

    let mut edits = Edits::new();
    edits.insert(edited.to_string(), replacement.clone().into_bytes());
    assert_eq!(pkg.rewrite(&out, &edits).unwrap(), 1);

    // Every other entry survives untouched...
    assert_entries_identical(&manifest(&src), &manifest(&out), &[edited]);

    // ...and the edited one carries exactly the new content.
    let after = Package::open(&out).unwrap();
    assert_eq!(after.read_text(edited).unwrap(), replacement);

    // The neighbouring parts are still readable as themselves.
    assert_eq!(
        after
            .read_bytes("ppt/embeddings/Microsoft_Excel_Sheet1.xlsx")
            .unwrap(),
        pkg.read_bytes("ppt/embeddings/Microsoft_Excel_Sheet1.xlsx")
            .unwrap(),
        "the embedded workbook changed"
    );
}

#[test]
fn a_rewrite_is_reproducible() {
    let src = fixture(TORTURE);
    let scratch = Scratch::new("repeat");
    let (a, b) = (scratch.join("a.pptx"), scratch.join("b.pptx"));

    let pkg = Package::open(&src).unwrap();
    pkg.rewrite(&a, &Edits::new()).unwrap();
    pkg.rewrite(&b, &Edits::new()).unwrap();

    assert!(
        std::fs::read(&a).unwrap() == std::fs::read(&b).unwrap(),
        "two rewrites of one input differ; the writer is not deterministic"
    );
}

#[test]
fn rewriting_is_idempotent() {
    // Repairing an already-repaired document must be a no-op. The rewrite of a
    // rewrite has to be a fixed point, or `repair` cannot safely be re-run.
    let scratch = Scratch::new("idempotent");
    let (once, twice) = (scratch.join("1.pptx"), scratch.join("2.pptx"));

    Package::open(fixture(TORTURE))
        .unwrap()
        .rewrite(&once, &Edits::new())
        .unwrap();
    Package::open(&once)
        .unwrap()
        .rewrite(&twice, &Edits::new())
        .unwrap();

    assert!(
        std::fs::read(&once).unwrap() == std::fs::read(&twice).unwrap(),
        "a second rewrite changed the file; the writer is not a fixed point"
    );
}

#[test]
fn refuses_to_overwrite_its_own_source() {
    let src = fixture(TORTURE);
    let before = std::fs::read(&src).unwrap();

    let err = Package::open(&src)
        .unwrap()
        .rewrite(&src, &Edits::new())
        .unwrap_err();

    assert!(
        matches!(err, mirsam_core::error::Error::WouldOverwriteSource),
        "expected WouldOverwriteSource, got {err:?}"
    );
    assert_eq!(
        std::fs::read(&src).unwrap(),
        before,
        "the source was modified despite the refusal"
    );
}

#[test]
fn an_edit_naming_an_unknown_part_is_an_error() {
    // Silently ignoring it would let a caller believe a repair was applied.
    let scratch = Scratch::new("unknown");
    let out = scratch.join("out.pptx");

    let mut edits = Edits::new();
    edits.insert("ppt/slides/slide99.xml".into(), b"<x/>".to_vec());

    let err = Package::open(fixture(TORTURE))
        .unwrap()
        .rewrite(&out, &edits)
        .unwrap_err();

    assert!(
        format!("{err}").contains("slide99"),
        "unhelpful error: {err}"
    );
    assert!(!out.exists(), "a failed rewrite left an output file behind");
}

#[test]
fn a_non_package_is_rejected_on_open() {
    let scratch = Scratch::new("notzip");
    let path = scratch.join("not-a-deck.pptx");
    std::fs::write(&path, b"this is not a ZIP").unwrap();
    assert!(Package::open(&path).is_err());
}
